In [1]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换（整形<浮点型<字符串）

In [8]:
list = [1, 2, 3, 4]
list_array = np.array(list)
list_array

array([1, 2, 3, 4])

In [1]:
list2 = [1, 2, 3, 4, 5.1]
list2_array = np.array(list2)
list2_array

NameError: name 'np' is not defined

ndarray基本属性操作

In [10]:
type(list_array)

numpy.ndarray

In [11]:
list_array.dtype # ndarray 对象的元素类型

dtype('int64')

In [12]:
list_array.itemsize # ndarray 对象中每个元素的大小，以字节为单位

8

In [15]:
list_array.shape # 数组的维度，对于矩阵，n 行 m 列

(4,)

In [16]:
list_array.size # 数组元素的总个数，相当于 .shape 中 n*m 的值

4

In [17]:
np.size(list_array)

4

In [18]:
np.shape(list_array)

(4,)

In [20]:
list_array.ndim # 秩，即轴的数量或维度的数量

1

In [21]:
list_array

array([1, 2, 3, 4])

In [23]:
list_array.fill(0) # 对数组填充
list_array

array([0, 0, 0, 0])

索引与切片:跟Python都是一样的 还是从0开始的

In [24]:
tang_list = [1,2,3,4,5,6]
tang_array = np.array(tang_list)
tang_array[0]

1

In [25]:
tang_array[1:3]

array([2, 3])

In [26]:
tang_array[-3:]

array([4, 5, 6])

矩阵格式（多维的形式）

In [27]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
tang_array.shape

(3, 3)

In [29]:
tang_array.size

9

In [30]:
tang_array.ndim

2

In [32]:
tang_array[1,1] # 二维数组索引要两个元素，第1行第1列

5

In [33]:
tang_array[1,1] = 10 # 替换
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [34]:
tang_array[1] # 索引第一行

array([ 4, 10,  6])

In [35]:
tang_array[:,1] # 索引所有行的第2个元素（索引从0开始）

array([ 2, 10,  8])

In [36]:
tang_array[0,0:2]

array([1, 2])

In [37]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

不同的赋值操作

In [38]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

A_1 = A_2 等号代表储存在同一个区域，改变任意一个，区域内的都会改变

In [39]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [40]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [43]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

.copy赋值后储存地址不同

In [44]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [45]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [46]:
tang_array = np.arange(0,100,10) # 从0到100，间隔10
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
mask = np.array([0,0,0,0,0,0,1,1,1,1],dtype=bool)
mask

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [48]:
tang_array[mask] # 布尔类型索引（筛选）

array([60, 70, 80, 90])

In [50]:
random_array = np.random.rand(10) # 生成随机数
random_array

array([0.44996202, 0.78368004, 0.44239353, 0.91488089, 0.74673588,
       0.9232289 , 0.94295097, 0.90559852, 0.90406338, 0.30987296])

In [51]:
mask = random_array > 0.5 # 做判断，输出布尔类型
mask

array([False,  True, False,  True,  True,  True,  True,  True,  True,
       False])

In [52]:
tang_array[mask]

array([10, 30, 40, 50, 60, 70, 80])

In [53]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [54]:
np.where(tang_array > 30) # 取索引值

(array([3, 4]),)

In [55]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [56]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32) # 定义类型
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [57]:
tang_array.dtype

dtype('float32')

In [58]:
tang_array.nbytes

20

In [59]:
tang_array = np.array([1,10,3.5,'str'],dtype = np.object) # 类似于字符串类型
tang_array

array([1, 10, 3.5, 'str'], dtype=object)

In [60]:
tang_array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [68]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [69]:
tang_array

array([1, 2, 3, 4, 5])

In [70]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)

In [71]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [72]:
tang_array

array([1, 2, 3, 4, 5])

In [73]:
tang_array.astype(np.float32) # 类型转换

array([1., 2., 3., 4., 5.], dtype=float32)

In [74]:
tang_array 

array([1, 2, 3, 4, 5])