In [1]:
import numpy as np
tang_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [2]:
np.sort(tang_array) # 默认先从小到大排序

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [3]:
np.sort(tang_array,axis = 0) # 指定轴排序——列

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [4]:
np.sort(tang_array,axis = 1)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [15]:
tang_array

array([[ 1.5,  1.3,  7.5],
       [ 5.6,  7.8,  1.2]])

In [14]:
np.argsort(tang_array) # 排序索引顺序

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [5]:
tang_array = np.linspace(0,10,10) # 从0到10，元素个数
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [6]:
values = np.array([2.5,6.5,9.5])

In [7]:
np.searchsorted(tang_array,values) # 排序插入，返回插入位置索引

array([3, 6, 9])

In [9]:
tang_array = np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [14]:
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]]) # 第0列降序，第2列升序
index

array([1, 0, 2, 3])

In [15]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])