In [1]:
import numpy as np

In [2]:
x = np.array([5,5])
y = np.array([2,2])

In [3]:
np.multiply(x,y) # 对应元素乘法操作

array([10, 10])

In [4]:
x

array([5, 5])

In [5]:
y

array([2, 2])

1维的时候是内积计算

In [6]:
np.dot(x,y) # 矩阵乘法，但是当纬度为1时为内积运算

20

In [7]:
x.shape

(2,)

In [8]:
y.shape

(2,)

In [9]:
x.shape = 2,1

In [10]:
x

array([[5],
       [5]])

In [11]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [12]:
y.shape = 1,2
y

array([[2, 2]])

In [13]:
x

array([[5],
       [5]])

二维的时候就是矩阵计算

In [14]:
print (x.shape)
print (y.shape)

(2, 1)
(1, 2)


In [15]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [16]:
np.dot(y,x)

array([[20]])

In [17]:
x = np.array([2,1,1])
y = np.array([[1,2,3],[4,5,6]])
print (x * y)
np.multiply(x,y)

[[2 2 3]
 [8 5 6]]


array([[2, 2, 3],
       [8, 5, 6]])

In [18]:
y = np.array([1,1,1,4])
x = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

In [19]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [20]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [21]:
np.logical_not(x,y)

array([0, 0, 0, 0])